[package]
name = "norm-checker"
version = "0.1.0"
authors = ["Alexandre Demeester <alexandre.demeester@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
